export const fieldHelp: Record<string, { label: string; helper: string; placeholder: string; unit?: string; validation: string }> = {
  supplierName: {
    label: "Supplier Name",
    helper: "The company, factory, or vendor that can provide the product.",
    placeholder: "Example: Shenzhen Precision Works",
    validation: "Supplier name is required.",
  },
  country: {
    label: "Country",
    helper: "The country where the supplier, demand hub, or logistics node is located.",
    placeholder: "Example: Vietnam",
    validation: "Country is required for country risk and map placement.",
  },
  region: {
    label: "Region",
    helper: "The sourcing region used for diversification and risk grouping.",
    placeholder: "Example: Southeast Asia",
    validation: "Region is required.",
  },
  productCategory: {
    label: "Product Category",
    helper: "The product family or category this supplier supports.",
    placeholder: "Example: PCB assemblies",
    validation: "Use a clear category so scenarios remain readable.",
  },
  baseUnitCost: {
    label: "Base Unit Cost",
    helper: "The supplier's quoted price per unit before freight, duties, insurance, and risk premiums.",
    placeholder: "Example: 165",
    unit: "USD/unit",
    validation: "Unit cost cannot be negative.",
  },
  moq: {
    label: "MOQ",
    helper: "Minimum order quantity required by the supplier.",
    placeholder: "Example: 2000",
    unit: "units",
    validation: "MOQ cannot be negative.",
  },
  capacity: {
    label: "Monthly Capacity",
    helper: "The maximum units the supplier can support in a month.",
    placeholder: "Example: 18000",
    unit: "units/month",
    validation: "Capacity cannot be negative.",
  },
  leadTime: {
    label: "Lead Time",
    helper: "The expected number of days from purchase order release to delivery at the demand location.",
    placeholder: "Example: 21",
    unit: "days",
    validation: "Lead time must be greater than 0 for active suppliers.",
  },
  reliability: {
    label: "Reliability",
    helper: "Estimated percentage of orders the supplier delivers on time and in full.",
    placeholder: "Example: 92",
    unit: "%",
    validation: "Reliability must be between 0 and 100.",
  },
  qualityScore: {
    label: "Quality Score",
    helper: "Supplier quality performance score based on defects, returns, and audit results.",
    placeholder: "Example: 88",
    unit: "0-100",
    validation: "Quality score must be between 0 and 100.",
  },
  esgScore: {
    label: "ESG Score",
    helper: "Environmental, social, and governance score for supplier sustainability.",
    placeholder: "Example: 72",
    unit: "0-100",
    validation: "ESG score must be between 0 and 100.",
  },
  financialHealth: {
    label: "Financial Health Score",
    helper: "Estimate of supplier solvency and business continuity strength.",
    placeholder: "Example: 80",
    unit: "0-100",
    validation: "Financial health must be between 0 and 100.",
  },
  tariffRate: {
    label: "Tariff Rate",
    helper: "Import duty percentage applied to the supplier's base unit cost.",
    placeholder: "Example: 5",
    unit: "%",
    validation: "Tariff rate cannot be negative.",
  },
  insuranceRate: {
    label: "Insurance Rate",
    helper: "Cargo insurance percentage applied to the supplier's base unit cost.",
    placeholder: "Example: 1.5",
    unit: "%",
    validation: "Insurance rate cannot be negative.",
  },
  monthlyDemand: {
    label: "Monthly Demand",
    helper: "The number of units this demand hub needs each month.",
    placeholder: "Example: 12000",
    unit: "units/month",
    validation: "Demand cannot be negative.",
  },
  serviceLevelTarget: {
    label: "Service-Level Target",
    helper: "Minimum acceptable delivery performance for this demand hub.",
    placeholder: "Example: 95",
    unit: "%",
    validation: "Service target must be between 0 and 100.",
  },
  maxLeadTime: {
    label: "Max Acceptable Lead Time",
    helper: "Longest acceptable replenishment time for this demand hub.",
    placeholder: "Example: 35",
    unit: "days",
    validation: "Lead time target cannot be negative.",
  },
  freightCost: {
    label: "Freight Cost per Unit",
    helper: "Transportation cost allocated to each unit on this route.",
    placeholder: "Example: 18",
    unit: "USD/unit",
    validation: "Freight cost cannot be negative.",
  },
  transitTime: {
    label: "Transit Time",
    helper: "Expected days in transit from origin to destination.",
    placeholder: "Example: 21",
    unit: "days",
    validation: "Transit time must be greater than 0 for active routes.",
  },
  delayProbability: {
    label: "Delay Probability",
    helper: "Estimated chance that the route misses the expected transit time.",
    placeholder: "Example: 15",
    unit: "%",
    validation: "Delay probability must be between 0 and 100.",
  },
  riskScore: {
    label: "Risk Score",
    helper: "A normalized 0-100 estimate where higher means more exposure.",
    placeholder: "Example: 45",
    unit: "0-100",
    validation: "Risk score must be between 0 and 100.",
  },
};
