export interface GlossaryEntry {
  term: string;
  definition: string;
  whyItMatters: string;
  example: string;
  predictionImpact: string;
}

export const glossaryEntries: GlossaryEntry[] = [
  {
    term: "Landed Cost",
    definition: "The full cost of getting one unit from supplier to destination.",
    whyItMatters: "A cheap supplier may become expensive after freight, tariffs, insurance, and risk premiums.",
    example: "$165 supplier cost + $12 freight + $8 tariff + $2 insurance = $187 landed cost.",
    predictionImpact: "Used in total cost, risk-adjusted cost, and supplier recommendation.",
  },
  {
    term: "Risk-adjusted Cost",
    definition: "Landed cost increased by risk exposure from supplier, country, route, and active events.",
    whyItMatters: "It makes risk visible in financial comparisons.",
    example: "$187 landed cost with 20% normalized risk = $224.40 risk-adjusted cost.",
    predictionImpact: "Used to compare suppliers when disruptions, FX, or political risks are active.",
  },
  {
    term: "Demand Hub",
    definition: "A customer, market, plant, warehouse, or region that needs delivered supply.",
    whyItMatters: "Predictions need a destination and demand volume before routes can be evaluated.",
    example: "US East DC requiring 12,000 units per month.",
    predictionImpact: "Creates demand volume, service targets, lead-time thresholds, and inventory context.",
  },
  {
    term: "Route/Lane",
    definition: "A connection from a supplier to a demand hub using a transport mode.",
    whyItMatters: "Freight cost, transit time, emissions, and logistics risk are lane-specific.",
    example: "Vietnam supplier to US West DC by sea with 21-day transit.",
    predictionImpact: "Feeds lead time, landed cost, route risk, emissions, and demand coverage.",
  },
  {
    term: "Transport Mode",
    definition: "The freight method used on a lane: sea, air, land, or multimodal.",
    whyItMatters: "Mode changes cost, speed, risk, and emissions.",
    example: "Air freight may cut transit time but increase cost and emissions.",
    predictionImpact: "Changes freight cost, lead time, emissions, and risk scoring.",
  },
  {
    term: "Monthly Capacity",
    definition: "The number of units a supplier can produce or reserve in a month.",
    whyItMatters: "A supplier cannot cover demand beyond available capacity without overcapacity risk.",
    example: "Supplier can commit 8,000 units per month.",
    predictionImpact: "Used in capacity utilization, shortage risk, and allocation warnings.",
  },
  {
    term: "MOQ",
    definition: "Minimum order quantity required by the supplier.",
    whyItMatters: "Small allocations may be infeasible when MOQ is high.",
    example: "MOQ of 2,000 units per order.",
    predictionImpact: "Affects feasible supplier allocation and sourcing recommendations.",
  },
  {
    term: "Reliability",
    definition: "Estimated percentage of orders delivered on time and in full.",
    whyItMatters: "Reliable suppliers reduce service failures and shortage risk.",
    example: "92% OTIF reliability.",
    predictionImpact: "Feeds service level prediction, resilience, and recommendation scoring.",
  },
  {
    term: "ESG Score",
    definition: "A sustainability and governance score for a supplier or network.",
    whyItMatters: "ESG constraints can make a low-cost option unacceptable.",
    example: "Supplier ESG score of 78 out of 100.",
    predictionImpact: "Used in ESG weighted average and ESG-oriented optimization.",
  },
  {
    term: "Political Risk",
    definition: "Country or regional instability that can affect sourcing continuity.",
    whyItMatters: "Political disruptions can increase lead time, costs, or supply interruption risk.",
    example: "A score of 65 indicates elevated geopolitical exposure.",
    predictionImpact: "Feeds supplier risk, risk-adjusted cost, and resilience.",
  },
  {
    term: "Currency Risk",
    definition: "Exposure to exchange-rate volatility in supplier markets.",
    whyItMatters: "FX swings can change real supplier cost after contract signing.",
    example: "A 6% currency volatility event on Turkey routes.",
    predictionImpact: "Adds risk premium and cost uncertainty.",
  },
  {
    term: "Natural Disaster Risk",
    definition: "Weather, seismic, flood, storm, or climate exposure for a supplier or route.",
    whyItMatters: "Physical disruptions can stop production or delay freight.",
    example: "Monsoon risk affecting South Asia lanes.",
    predictionImpact: "Feeds risk score, delay risk, service prediction, and resilience.",
  },
  {
    term: "Tariff Rate",
    definition: "Duty percentage applied to imported supplier goods.",
    whyItMatters: "Tariffs can erase unit-cost advantages.",
    example: "5% tariff on a $200 unit adds $10.",
    predictionImpact: "Added directly to landed cost.",
  },
  {
    term: "Insurance Rate",
    definition: "Cargo insurance percentage applied to the supplier unit value.",
    whyItMatters: "High-risk lanes often require higher insurance premiums.",
    example: "1.5% insurance on a $200 item adds $3.",
    predictionImpact: "Added to landed cost and indirectly reflects route risk.",
  },
  {
    term: "Service Level Target",
    definition: "The minimum acceptable delivery reliability for a demand hub.",
    whyItMatters: "Service-critical hubs may require higher-cost but more reliable sourcing.",
    example: "95% target service level for a hospital distribution hub.",
    predictionImpact: "Compared against service level prediction for warnings.",
  },
  {
    term: "Safety Stock",
    definition: "Inventory buffer held to absorb demand or supply variability.",
    whyItMatters: "More buffer can protect service but increases carrying cost.",
    example: "15 days of safety stock.",
    predictionImpact: "Improves service prediction and reduces shortage risk.",
  },
  {
    term: "Freight Cost Per Unit",
    definition: "Transportation cost allocated to each unit on a route.",
    whyItMatters: "Freight can dominate total cost for bulky or expedited goods.",
    example: "$18 per unit by sea freight.",
    predictionImpact: "Added directly to landed cost and risk-adjusted cost.",
  },
  {
    term: "Transit Time",
    definition: "Expected days spent moving goods from origin to destination.",
    whyItMatters: "Transit time affects inventory, delivery promise, and responsiveness.",
    example: "21 days from supplier port to customer hub.",
    predictionImpact: "Used in average lead time and service prediction.",
  },
  {
    term: "Delay Probability",
    definition: "Estimated chance that the route arrives later than planned.",
    whyItMatters: "High delay probability lowers service reliability.",
    example: "15% delay probability on a congested ocean lane.",
    predictionImpact: "Feeds route risk, service prediction, and risk premium.",
  },
  {
    term: "Customs Risk",
    definition: "Chance of import/export clearance delays or compliance holds.",
    whyItMatters: "Customs delays can add unpredictable lead time.",
    example: "30 out of 100 customs risk for a regulated product lane.",
    predictionImpact: "Feeds logistics risk and lead-time warnings.",
  },
  {
    term: "Port Congestion Risk",
    definition: "Likelihood of queueing, dwell time, or throughput constraints at a hub.",
    whyItMatters: "Congestion can add days even when supplier production is stable.",
    example: "60 congestion score at a strained container port.",
    predictionImpact: "Feeds route risk and predicted lead time.",
  },
  {
    term: "Emissions Factor",
    definition: "Estimated emissions per unit moved on a route.",
    whyItMatters: "Transport mode can materially change ESG outcomes.",
    example: "0.45 kg CO2e per unit by sea freight.",
    predictionImpact: "Reduces ESG weighted average and supports ESG optimization.",
  },
  {
    term: "Risk Event",
    definition: "A disruption scenario that affects suppliers, routes, countries, or demand hubs.",
    whyItMatters: "Stress testing shows whether the sourcing plan survives real-world disruptions.",
    example: "Port strike adding 7 days and 8% freight cost.",
    predictionImpact: "Changes cost, lead time, reliability, risk, and recommendations.",
  },
  {
    term: "Probability",
    definition: "Likelihood that a risk event occurs or remains relevant.",
    whyItMatters: "High-probability events deserve more planning weight.",
    example: "High probability for a known congestion event.",
    predictionImpact: "Amplifies risk score impact.",
  },
  {
    term: "Severity",
    definition: "How strongly a risk event disrupts operations if it occurs.",
    whyItMatters: "Low-probability high-severity events may still require mitigation.",
    example: "80 severity for a route closure.",
    predictionImpact: "Used to communicate risk intensity and stress-test priority.",
  },
  {
    term: "Demand Coverage",
    definition: "The percentage of total demand connected to active supplier routes.",
    whyItMatters: "A network cannot serve demand without active lanes.",
    example: "8,000 routed units against 10,000 demand = 80% coverage.",
    predictionImpact: "Feeds shortage risk and network readiness warnings.",
  },
  {
    term: "Network Resilience",
    definition: "A score for how well the network can absorb disruptions.",
    whyItMatters: "Diversified suppliers, regions, modes, and capacity headroom improve resilience.",
    example: "A dual-source network across two regions has higher resilience.",
    predictionImpact: "Used in scorecards and resilience optimization.",
  },
  {
    term: "Recommended Allocation",
    definition: "Suggested percentage mix across suppliers based on selected weights.",
    whyItMatters: "It translates cost/risk/service trade-offs into an actionable sourcing plan.",
    example: "50% Supplier A, 30% Supplier B, 20% Supplier C.",
    predictionImpact: "Generated by heuristic scoring once the network is complete enough.",
  },
  {
    term: "Optimization Weights",
    definition: "Priority sliders for cost, lead time, risk, reliability, ESG, capacity, and resilience.",
    whyItMatters: "Different business goals require different sourcing trade-offs.",
    example: "Increase risk weight to favor safer suppliers.",
    predictionImpact: "Changes the recommended allocation and scenario comparisons.",
  },
  {
    term: "Total Budget",
    definition: "Maximum spend available for the sourcing plan.",
    whyItMatters: "A plan can be operationally strong but financially infeasible.",
    example: "$2.5M monthly sourcing budget.",
    predictionImpact: "Triggers budget warnings and recommendation decisions.",
  },
  {
    term: "Price Concession",
    definition: "Negotiated supplier price reduction.",
    whyItMatters: "Lower price may come with reliability or commitment trade-offs.",
    example: "-3% unit cost in exchange for longer commitment.",
    predictionImpact: "Reduces landed cost but can be modeled with reliability or lock-in penalties.",
  },
  {
    term: "Dual Sourcing",
    definition: "Splitting supply across more than one supplier.",
    whyItMatters: "Dual sourcing reduces dependency on one supplier or country.",
    example: "60% primary supplier, 40% backup supplier.",
    predictionImpact: "Improves resilience and can reduce disruption impact.",
  },
];

export const fieldHelp: Record<string, { label: string; helper: string; placeholder: string; unit?: string; validation: string }> = {
  supplierName: {
    label: "Supplier Name",
    helper: "The company, factory, or vendor that can provide the product.",
    placeholder: "Example: Shenzhen Precision Works",
    validation: "Supplier name is required.",
  },
  country: {
    label: "Country",
    helper: "The country where the supplier, demand hub, or logistics node is located.",
    placeholder: "Example: Vietnam",
    validation: "Country is required for country risk and map placement.",
  },
  region: {
    label: "Region",
    helper: "The sourcing region used for diversification and risk grouping.",
    placeholder: "Example: Southeast Asia",
    validation: "Region is required.",
  },
  productCategory: {
    label: "Product Category",
    helper: "The product family or category this supplier supports.",
    placeholder: "Example: PCB assemblies",
    validation: "Use a clear category so scenarios remain readable.",
  },
  baseUnitCost: {
    label: "Base Unit Cost",
    helper: "The supplier's quoted price per unit before freight, duties, insurance, and risk premiums.",
    placeholder: "Example: 165",
    unit: "USD/unit",
    validation: "Unit cost cannot be negative.",
  },
  moq: {
    label: "MOQ",
    helper: "Minimum order quantity required by the supplier.",
    placeholder: "Example: 2000",
    unit: "units",
    validation: "MOQ cannot be negative.",
  },
  capacity: {
    label: "Monthly Capacity",
    helper: "The maximum units the supplier can support in a month.",
    placeholder: "Example: 18000",
    unit: "units/month",
    validation: "Capacity cannot be negative.",
  },
  leadTime: {
    label: "Lead Time",
    helper: "The expected number of days from purchase order release to delivery at the demand location.",
    placeholder: "Example: 21",
    unit: "days",
    validation: "Lead time must be greater than 0 for active suppliers.",
  },
  reliability: {
    label: "Reliability",
    helper: "Estimated percentage of orders the supplier delivers on time and in full.",
    placeholder: "Example: 92",
    unit: "%",
    validation: "Reliability must be between 0 and 100.",
  },
  qualityScore: {
    label: "Quality Score",
    helper: "Supplier quality performance score based on defects, returns, and audit results.",
    placeholder: "Example: 88",
    unit: "0-100",
    validation: "Quality score must be between 0 and 100.",
  },
  esgScore: {
    label: "ESG Score",
    helper: "Environmental, social, and governance score for supplier sustainability.",
    placeholder: "Example: 72",
    unit: "0-100",
    validation: "ESG score must be between 0 and 100.",
  },
  financialHealth: {
    label: "Financial Health Score",
    helper: "Estimate of supplier solvency and business continuity strength.",
    placeholder: "Example: 80",
    unit: "0-100",
    validation: "Financial health must be between 0 and 100.",
  },
  tariffRate: {
    label: "Tariff Rate",
    helper: "Import duty percentage applied to the supplier's base unit cost.",
    placeholder: "Example: 5",
    unit: "%",
    validation: "Tariff rate cannot be negative.",
  },
  insuranceRate: {
    label: "Insurance Rate",
    helper: "Cargo insurance percentage applied to the supplier's base unit cost.",
    placeholder: "Example: 1.5",
    unit: "%",
    validation: "Insurance rate cannot be negative.",
  },
  monthlyDemand: {
    label: "Monthly Demand",
    helper: "The number of units this demand hub needs each month.",
    placeholder: "Example: 12000",
    unit: "units/month",
    validation: "Demand cannot be negative.",
  },
  serviceLevelTarget: {
    label: "Service-Level Target",
    helper: "Minimum acceptable delivery performance for this demand hub.",
    placeholder: "Example: 95",
    unit: "%",
    validation: "Service target must be between 0 and 100.",
  },
  maxLeadTime: {
    label: "Max Acceptable Lead Time",
    helper: "Longest acceptable replenishment time for this demand hub.",
    placeholder: "Example: 35",
    unit: "days",
    validation: "Lead time target cannot be negative.",
  },
  freightCost: {
    label: "Freight Cost per Unit",
    helper: "Transportation cost allocated to each unit on this route.",
    placeholder: "Example: 18",
    unit: "USD/unit",
    validation: "Freight cost cannot be negative.",
  },
  transitTime: {
    label: "Transit Time",
    helper: "Expected days in transit from origin to destination.",
    placeholder: "Example: 21",
    unit: "days",
    validation: "Transit time must be greater than 0 for active routes.",
  },
  delayProbability: {
    label: "Delay Probability",
    helper: "Estimated chance that the route misses the expected transit time.",
    placeholder: "Example: 15",
    unit: "%",
    validation: "Delay probability must be between 0 and 100.",
  },
  riskScore: {
    label: "Risk Score",
    helper: "A normalized 0-100 estimate where higher means more exposure.",
    placeholder: "Example: 45",
    unit: "0-100",
    validation: "Risk score must be between 0 and 100.",
  },
};
