export const countryOptions = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const regionOptions = [
  "North America",
  "Latin America",
  "Caribbean",
  "Western Europe",
  "Northern Europe",
  "Southern Europe",
  "Eastern Europe",
  "Middle East",
  "North Africa",
  "West Africa",
  "Central Africa",
  "East Africa",
  "Southern Africa",
  "Central Asia",
  "South Asia",
  "East Asia",
  "Southeast Asia",
  "Oceania",
  "Global",
  "Other",
];

export const productCategoryOptions = [
  "Aerospace Components",
  "Agricultural Inputs",
  "Apparel",
  "Automotive Parts",
  "Batteries and Energy Storage",
  "Building Materials",
  "Chemicals",
  "Consumer Electronics",
  "Electrical Components",
  "Food and Beverage",
  "Furniture",
  "Industrial Electronics",
  "Industrial Machinery",
  "Medical Devices",
  "Metals and Fabrication",
  "Packaging",
  "Pharmaceuticals",
  "Plastics and Resins",
  "Raw Materials",
  "Semiconductors",
  "Textiles",
  "Other",
];

const countryRegionMap: Record<string, string> = {
  Canada: "North America",
  Mexico: "North America",
  "United States": "North America",
  "United States of America": "North America",
  Brazil: "Latin America",
  Argentina: "Latin America",
  Chile: "Latin America",
  Colombia: "Latin America",
  Peru: "Latin America",
  Venezuela: "Latin America",
  Uruguay: "Latin America",
  Paraguay: "Latin America",
  Bolivia: "Latin America",
  Ecuador: "Latin America",
  Germany: "Western Europe",
  France: "Western Europe",
  Netherlands: "Western Europe",
  Belgium: "Western Europe",
  Switzerland: "Western Europe",
  Austria: "Western Europe",
  "United Kingdom": "Northern Europe",
  Ireland: "Northern Europe",
  Denmark: "Northern Europe",
  Sweden: "Northern Europe",
  Norway: "Northern Europe",
  Finland: "Northern Europe",
  Spain: "Southern Europe",
  Italy: "Southern Europe",
  Portugal: "Southern Europe",
  Greece: "Southern Europe",
  Poland: "Eastern Europe",
  Czechia: "Eastern Europe",
  Hungary: "Eastern Europe",
  Romania: "Eastern Europe",
  Ukraine: "Eastern Europe",
  Russia: "Eastern Europe",
  China: "East Asia",
  Japan: "East Asia",
  "South Korea": "East Asia",
  Taiwan: "East Asia",
  Mongolia: "East Asia",
  India: "South Asia",
  Pakistan: "South Asia",
  Bangladesh: "South Asia",
  "Sri Lanka": "South Asia",
  Nepal: "South Asia",
  Thailand: "Southeast Asia",
  Vietnam: "Southeast Asia",
  Malaysia: "Southeast Asia",
  Singapore: "Southeast Asia",
  Indonesia: "Southeast Asia",
  Philippines: "Southeast Asia",
  Cambodia: "Southeast Asia",
  Laos: "Southeast Asia",
  Myanmar: "Southeast Asia",
  Australia: "Oceania",
  "New Zealand": "Oceania",
  Turkey: "Middle East",
  Israel: "Middle East",
  "Saudi Arabia": "Middle East",
  "United Arab Emirates": "Middle East",
  Qatar: "Middle East",
  Oman: "Middle East",
  Egypt: "North Africa",
  Morocco: "North Africa",
  Tunisia: "North Africa",
  Algeria: "North Africa",
  Nigeria: "West Africa",
  Ghana: "West Africa",
  Senegal: "West Africa",
  Kenya: "East Africa",
  Ethiopia: "East Africa",
  Tanzania: "East Africa",
  Uganda: "East Africa",
  "South Africa": "Southern Africa",
  Botswana: "Southern Africa",
  Namibia: "Southern Africa",
};

export const normalizeCountryName = (country: string) => {
  const aliases: Record<string, string> = {
    "United States of America": "United States",
    "W. Sahara": "Western Sahara",
    "Dem. Rep. Congo": "Democratic Republic of the Congo",
    Congo: "Congo",
    "Dominican Rep.": "Dominican Republic",
    "Central African Rep.": "Central African Republic",
    "Eq. Guinea": "Equatorial Guinea",
    eSwatini: "Eswatini",
    Somaliland: "Somalia",
    "Bosnia and Herz.": "Bosnia and Herzegovina",
    Macedonia: "North Macedonia",
    Czechia: "Czechia",
    "S. Sudan": "South Sudan",
    "Solomon Is.": "Solomon Islands",
  };
  return aliases[country] ?? country;
};

export const getRegionForCountry = (country: string) => countryRegionMap[normalizeCountryName(country)] ?? "";
