import type { ForecastAssumptions, NegotiationLever, ProductDetails, Scenario, TransportMode, TransportProfile } from "./types";

export const transportModes: TransportMode[] = ["Sea", "Air", "Land", "Multimodal"];

export const modeDefaults: Record<TransportMode, TransportProfile> = {
  Sea: {
    mode: "Sea",
    freightCost: 0,
    transitTime: 0,
    delayProbability: 0,
    emissionsFactor: 0,
    congestionRisk: 0,
  },
  Air: {
    mode: "Air",
    freightCost: 0,
    transitTime: 0,
    delayProbability: 0,
    emissionsFactor: 0,
    congestionRisk: 0,
  },
  Land: {
    mode: "Land",
    freightCost: 0,
    transitTime: 0,
    delayProbability: 0,
    emissionsFactor: 0,
    congestionRisk: 0,
  },
  Multimodal: {
    mode: "Multimodal",
    freightCost: 0,
    transitTime: 0,
    delayProbability: 0,
    emissionsFactor: 0,
    congestionRisk: 0,
  },
};

export const blankForecastAssumptions: ForecastAssumptions = {
  demandGrowthPct: 0,
  costInflationPct: 0,
  riskTrendPct: 0,
  serviceDriftPct: 0,
  seasonalityNotes: "",
};

export const blankProductDetails: ProductDetails = {
  name: "",
  sku: "",
  category: "",
  customCategory: "",
  descriptors: "",
  specification: "",
  complianceRequirements: "",
  qualityRequirements: "",
  unitOfMeasure: "units",
  annualVolume: 0,
  notes: "",
};

export const createBlankNegotiationLever = (): NegotiationLever => ({
  id: `lever-${Date.now()}`,
  name: "",
  effect: "",
  active: false,
  unitCostImpactPct: 0,
  freightCostImpactPct: 0,
  leadTimeImpactPct: 0,
  reliabilityImpactPct: 0,
  resilienceImpact: 0,
  serviceLevelImpact: 0,
  emissionsImpactPct: 0,
  managementCostImpactPct: 0,
});

export const createSeedScenario = (): Scenario => createBlankScenario();

const balancedWeights: Scenario["weights"] = { cost: 20, leadTime: 15, risk: 20, reliability: 15, esg: 10, capacity: 10, resilience: 10 };

const exampleTransportOverrides = () => ({
  Sea: { mode: "Sea" as const, freightCost: 5.8, transitTime: 23, delayProbability: 18, emissionsFactor: 0.08, congestionRisk: 24 },
  Air: { mode: "Air" as const, freightCost: 18.6, transitTime: 4, delayProbability: 9, emissionsFactor: 0.82, congestionRisk: 14 },
  Land: { mode: "Land" as const, freightCost: 3.7, transitTime: 8, delayProbability: 12, emissionsFactor: 0.22, congestionRisk: 18 },
  Multimodal: { mode: "Multimodal" as const, freightCost: 7.2, transitTime: 17, delayProbability: 15, emissionsFactor: 0.16, congestionRisk: 22 },
});

export const createBlankScenario = (): Scenario => {
  return {
    id: `blank-${Date.now()}`,
    name: "Blank Sourcing Network",
    horizonDays: 90,
    optimizationGoal: "Best balanced",
    weights: balancedWeights,
    budget: {
      monthlyDemand: 0,
      budget: 0,
      maxAverageLeadTime: 0,
      minServiceLevel: 0,
      maxSupplierAllocation: 0,
      minEsgScore: 0,
      safetyStockTarget: 0,
      currentInventory: 0,
      targetDeliveryDate: "",
    },
    suppliers: [],
    demandHubs: [],
    logisticsHubs: [],
    routes: [],
    riskEvents: [],
    levers: [],
    regionalRiskProfiles: [],
    forecastAssumptions: { ...blankForecastAssumptions },
    productDetails: { ...blankProductDetails },
    importedFiles: [],
    auditTrail: [],
    updatedAt: new Date().toISOString(),
  };
};

export const createExampleScenario = (): Scenario => {
  const updatedAt = new Date().toISOString();
  return {
    id: "example-command-center",
    name: "Example Command Center",
    horizonDays: 90,
    optimizationGoal: "Highest resilience",
    weights: { cost: 16, leadTime: 14, risk: 22, reliability: 18, esg: 8, capacity: 10, resilience: 12 },
    budget: {
      monthlyDemand: 20000,
      budget: 2100000,
      maxAverageLeadTime: 42,
      minServiceLevel: 88,
      maxSupplierAllocation: 65,
      minEsgScore: 70,
      safetyStockTarget: 21,
      currentInventory: 11800,
      targetDeliveryDate: "2026-10-15",
    },
    productDetails: {
      name: "Smart Sensor Control Module",
      sku: "SSCM-240",
      category: "Industrial Electronics",
      customCategory: "",
      descriptors: "IP67 enclosure, lithium battery backup, embedded wireless module, RoHS compliant, automotive-grade connector",
      specification: "90 x 54 x 22 mm module, ABS-PC housing, operating range -20 C to 70 C, firmware revision 4.2",
      complianceRequirements: "RoHS, REACH, FCC, CE, UN 38.3 battery documentation",
      qualityRequirements: "AQL 1.0 final inspection, 8D corrective action process, serialized traceability, burn-in sampling",
      unitOfMeasure: "units",
      annualVolume: 240000,
      notes: "Example dataset used to demonstrate a complete sourcing command-center view.",
    },
    suppliers: [
      {
        id: "example-supplier-tw",
        name: "Taiwan Precision Controls",
        country: "Taiwan",
        region: "East Asia",
        productCategory: "Industrial Electronics",
        baseUnitCost: 62,
        tariffRate: 3.5,
        freightCost: 5.8,
        insuranceRate: 1.2,
        leadTime: 16,
        reliability: 93,
        capacity: 11000,
        moq: 1200,
        esgScore: 78,
        politicalRisk: 44,
        currencyRisk: 22,
        naturalDisasterRisk: 38,
        financialHealth: 86,
        qualityScore: 94,
        notes: "Primary high-quality electronics supplier with strong process controls.",
        allocation: 50,
        included: true,
        transportMode: "Sea",
        coordinates: { x: 81.3, y: 37.6, lng: 121.0, lat: 23.8 },
        transportOverrides: exampleTransportOverrides(),
      },
      {
        id: "example-supplier-mx",
        name: "Monterrey Advanced Assembly",
        country: "Mexico",
        region: "North America",
        productCategory: "Industrial Electronics",
        baseUnitCost: 66,
        tariffRate: 0,
        freightCost: 3.7,
        insuranceRate: 0.9,
        leadTime: 9,
        reliability: 90,
        capacity: 8000,
        moq: 800,
        esgScore: 82,
        politicalRisk: 28,
        currencyRisk: 31,
        naturalDisasterRisk: 21,
        financialHealth: 81,
        qualityScore: 89,
        notes: "Nearshore supplier used for service protection and fast replenishment.",
        allocation: 30,
        included: true,
        transportMode: "Land",
        coordinates: { x: 29.1, y: 35.7, lng: -100.3, lat: 25.7 },
        transportOverrides: exampleTransportOverrides(),
      },
      {
        id: "example-supplier-pl",
        name: "Krakow Embedded Systems",
        country: "Poland",
        region: "Europe",
        productCategory: "Industrial Electronics",
        baseUnitCost: 69,
        tariffRate: 1.2,
        freightCost: 7.2,
        insuranceRate: 1,
        leadTime: 13,
        reliability: 91,
        capacity: 7000,
        moq: 900,
        esgScore: 86,
        politicalRisk: 18,
        currencyRisk: 24,
        naturalDisasterRisk: 12,
        financialHealth: 84,
        qualityScore: 92,
        notes: "Regional EU supply option supporting resilience and ESG goals.",
        allocation: 20,
        included: true,
        transportMode: "Multimodal",
        coordinates: { x: 55.6, y: 25.0, lng: 19.9, lat: 50.1 },
        transportOverrides: exampleTransportOverrides(),
      },
    ],
    demandHubs: [
      {
        id: "example-demand-us",
        name: "Northeast Fulfillment Hub",
        country: "United States",
        region: "North America",
        monthlyDemand: 12000,
        forecastDemand: 13200,
        serviceLevelTarget: 92,
        maxLeadTime: 38,
        currentInventory: 7200,
        safetyStock: 18,
        priorityLevel: "Critical",
        requiredDeliveryDate: "2026-09-30",
        coordinates: { x: 29.5, y: 29.5, lng: -73.9, lat: 40.7 },
        notes: "Highest-volume demand hub with strict service-level target.",
      },
      {
        id: "example-demand-nl",
        name: "Rotterdam EU Distribution",
        country: "Netherlands",
        region: "Europe",
        monthlyDemand: 8000,
        forecastDemand: 8800,
        serviceLevelTarget: 90,
        maxLeadTime: 35,
        currentInventory: 4600,
        safetyStock: 16,
        priorityLevel: "High",
        requiredDeliveryDate: "2026-10-08",
        coordinates: { x: 54.2, y: 25.6, lng: 4.5, lat: 51.9 },
        notes: "European hub balancing regional service and inventory efficiency.",
      },
    ],
    logisticsHubs: [
      {
        id: "example-logistics-la",
        name: "Port of Los Angeles",
        country: "United States",
        region: "North America",
        type: "Port",
        customsRisk: 18,
        congestionRisk: 42,
        handlingCost: 2.4,
        dwellTimeDays: 4,
        coordinates: { x: 29.7, y: 31.0, lng: -118.3, lat: 33.7 },
        notes: "Primary Pacific inbound port with moderate congestion risk.",
      },
      {
        id: "example-logistics-rtm",
        name: "Port of Rotterdam",
        country: "Netherlands",
        region: "Europe",
        type: "Port",
        customsRisk: 12,
        congestionRisk: 22,
        handlingCost: 2.1,
        dwellTimeDays: 3,
        coordinates: { x: 54.1, y: 25.5, lng: 4.1, lat: 51.9 },
        notes: "EU entry hub with strong customs performance.",
      },
    ],
    routes: [
      {
        id: "example-route-tw-us",
        supplierId: "example-supplier-tw",
        demandHubId: "example-demand-us",
        logisticsHubId: "example-logistics-la",
        originLabel: "Taiwan",
        destinationLabel: "Northeast Fulfillment Hub",
        mode: "Sea",
        active: true,
        allocationPct: 45,
        freightCost: 5.8,
        transitTime: 27,
        delayProbability: 22,
        customsRisk: 18,
        portCongestionRisk: 42,
        emissionsFactor: 0.08,
        distanceEstimate: 10800,
        from: { x: 81.3, y: 37.6, lng: 121.0, lat: 23.8 },
        to: { x: 29.5, y: 29.5, lng: -73.9, lat: 40.7 },
        via: { x: 29.7, y: 31.0, lng: -118.3, lat: 33.7 },
      },
      {
        id: "example-route-mx-us",
        supplierId: "example-supplier-mx",
        demandHubId: "example-demand-us",
        originLabel: "Mexico",
        destinationLabel: "Northeast Fulfillment Hub",
        mode: "Land",
        active: true,
        allocationPct: 55,
        freightCost: 3.7,
        transitTime: 8,
        delayProbability: 10,
        customsRisk: 16,
        portCongestionRisk: 8,
        emissionsFactor: 0.22,
        distanceEstimate: 3200,
        from: { x: 29.1, y: 35.7, lng: -100.3, lat: 25.7 },
        to: { x: 29.5, y: 29.5, lng: -73.9, lat: 40.7 },
      },
      {
        id: "example-route-tw-eu",
        supplierId: "example-supplier-tw",
        demandHubId: "example-demand-nl",
        logisticsHubId: "example-logistics-rtm",
        originLabel: "Taiwan",
        destinationLabel: "Rotterdam EU Distribution",
        mode: "Sea",
        active: true,
        allocationPct: 35,
        freightCost: 6.4,
        transitTime: 31,
        delayProbability: 19,
        customsRisk: 12,
        portCongestionRisk: 22,
        emissionsFactor: 0.08,
        distanceEstimate: 14200,
        from: { x: 81.3, y: 37.6, lng: 121.0, lat: 23.8 },
        to: { x: 54.2, y: 25.6, lng: 4.5, lat: 51.9 },
        via: { x: 54.1, y: 25.5, lng: 4.1, lat: 51.9 },
      },
      {
        id: "example-route-pl-eu",
        supplierId: "example-supplier-pl",
        demandHubId: "example-demand-nl",
        originLabel: "Poland",
        destinationLabel: "Rotterdam EU Distribution",
        mode: "Multimodal",
        active: true,
        allocationPct: 65,
        freightCost: 4.2,
        transitTime: 6,
        delayProbability: 9,
        customsRisk: 7,
        portCongestionRisk: 10,
        emissionsFactor: 0.16,
        distanceEstimate: 1180,
        from: { x: 55.6, y: 25.0, lng: 19.9, lat: 50.1 },
        to: { x: 54.2, y: 25.6, lng: 4.5, lat: 51.9 },
      },
    ],
    riskEvents: [
      {
        id: "example-risk-pacific",
        name: "Pacific Port Congestion",
        description: "Queueing pressure at trans-Pacific ports is increasing dwell time and freight premiums.",
        affectedCountries: ["Taiwan", "United States"],
        affectedSupplierIds: ["example-supplier-tw"],
        affectedDemandHubIds: ["example-demand-us"],
        affectedModes: ["Sea"],
        costImpactPct: 1.8,
        freightImpactPct: 8,
        leadTimeImpactDays: 4,
        reliabilityImpactPct: 3,
        riskScoreImpact: 8,
        severity: 68,
        confidenceLevel: 76,
        probability: "Medium",
        durationDays: 60,
        active: true,
        coordinates: { x: 45.5, y: 31.5, lng: -16.2, lat: 27.0 },
      },
      {
        id: "example-risk-currency",
        name: "Currency Volatility Watch",
        description: "Exchange-rate volatility could affect quoted component and logistics costs.",
        affectedCountries: ["Mexico", "Poland"],
        affectedSupplierIds: ["example-supplier-mx", "example-supplier-pl"],
        affectedDemandHubIds: [],
        affectedModes: [],
        costImpactPct: 1.2,
        freightImpactPct: 0,
        leadTimeImpactDays: 0,
        reliabilityImpactPct: 0,
        riskScoreImpact: 4,
        severity: 42,
        confidenceLevel: 62,
        probability: "Low",
        durationDays: 90,
        active: true,
        coordinates: { x: 36.0, y: 37.0, lng: -50.4, lat: 16.0 },
      },
    ],
    levers: [
      {
        id: "example-lever-dual-source",
        name: "Dual-source allocation cap",
        effect: "Limits single-supplier concentration and improves service resilience.",
        active: true,
        unitCostImpactPct: 0.8,
        freightCostImpactPct: 0,
        leadTimeImpactPct: -4,
        reliabilityImpactPct: 2,
        resilienceImpact: 9,
        serviceLevelImpact: 3,
        emissionsImpactPct: 0,
        managementCostImpactPct: 1.5,
      },
      {
        id: "example-lever-expedite",
        name: "Expedite recovery option",
        effect: "Reserves limited air capacity for critical shortage windows.",
        active: false,
        unitCostImpactPct: 0,
        freightCostImpactPct: 14,
        leadTimeImpactPct: -18,
        reliabilityImpactPct: 3,
        resilienceImpact: 4,
        serviceLevelImpact: 4,
        emissionsImpactPct: 8,
        managementCostImpactPct: 0.5,
      },
    ],
    regionalRiskProfiles: [
      {
        id: "example-profile-taiwan",
        country: "Taiwan",
        region: "East Asia",
        politicalRisk: 44,
        currencyRisk: 22,
        naturalDisasterRisk: 38,
        regulatoryRisk: 20,
        laborRisk: 16,
        infrastructureRisk: 12,
        notes: "Strong supplier base with geopolitical and weather exposure.",
      },
      {
        id: "example-profile-mexico",
        country: "Mexico",
        region: "North America",
        politicalRisk: 28,
        currencyRisk: 31,
        naturalDisasterRisk: 21,
        regulatoryRisk: 22,
        laborRisk: 19,
        infrastructureRisk: 24,
        notes: "Nearshore advantage with moderate cross-border and infrastructure risk.",
      },
      {
        id: "example-profile-poland",
        country: "Poland",
        region: "Europe",
        politicalRisk: 18,
        currencyRisk: 24,
        naturalDisasterRisk: 12,
        regulatoryRisk: 16,
        laborRisk: 14,
        infrastructureRisk: 11,
        notes: "Stable regional profile with good EU logistics coverage.",
      },
    ],
    forecastAssumptions: {
      demandGrowthPct: 8,
      costInflationPct: 3,
      riskTrendPct: 4,
      serviceDriftPct: -1,
      seasonalityNotes: "Q4 demand lift expected from industrial automation deployments; expedite option reserved for service recovery.",
    },
    auditTrail: [
      {
        id: "audit-example-loaded",
        at: updatedAt,
        change: "Example workspace loaded",
        reason: "Show a complete electronics component supplier award workflow with mock data.",
        recommendationImpact: "Recommendations are demonstration-only until replaced with company-entered or cited source data.",
      },
    ],
    importedFiles: [
      {
        id: "example-file-rfq",
        fileName: "example-rfq-and-network.xlsx",
        fileType: "xlsx",
        status: "Mapped",
        mappedFields: ["Suppliers", "Demand Hubs", "Routes", "Product Details", "Risk Events"],
        manualInputs: [],
        createdAt: updatedAt,
      },
    ],
    updatedAt,
  };
};
